/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IAdapter {
  export type ConfigStruct = { validatorSize: BigNumberish };

  export type ConfigStructOutput = [validatorSize: bigint] & {
    validatorSize: bigint;
  };
}

export interface IAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addValidator"
      | "addValidatorOracle"
      | "forceNextValidatorOracle"
      | "isValidatorOracle"
      | "removeValidatorOracle"
      | "setConfig"
      | "withdrawToL2"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddValidator"
      | "AddValidatorOracle"
      | "NextValidatorOracle"
      | "ReceiveEther"
      | "RemoveValidatorOracle"
      | "SetConfig"
      | "SetL2StakeTogether"
      | "SetValidatorSize"
      | "WithdrawToL2"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addValidator",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addValidatorOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "forceNextValidatorOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidatorOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidatorOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [IAdapter.ConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToL2",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addValidatorOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceNextValidatorOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidatorOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidatorOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToL2",
    data: BytesLike
  ): Result;
}

export namespace AddValidatorEvent {
  export type InputTuple = [
    oracle: AddressLike,
    amount: BigNumberish,
    publicKey: BytesLike,
    withdrawalCredentials: BytesLike,
    signature: BytesLike,
    depositDataRoot: BytesLike
  ];
  export type OutputTuple = [
    oracle: string,
    amount: bigint,
    publicKey: string,
    withdrawalCredentials: string,
    signature: string,
    depositDataRoot: string
  ];
  export interface OutputObject {
    oracle: string;
    amount: bigint;
    publicKey: string;
    withdrawalCredentials: string;
    signature: string;
    depositDataRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddValidatorOracleEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NextValidatorOracleEvent {
  export type InputTuple = [index: BigNumberish, account: AddressLike];
  export type OutputTuple = [index: bigint, account: string];
  export interface OutputObject {
    index: bigint;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiveEtherEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveValidatorOracleEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetConfigEvent {
  export type InputTuple = [config: IAdapter.ConfigStruct];
  export type OutputTuple = [config: IAdapter.ConfigStructOutput];
  export interface OutputObject {
    config: IAdapter.ConfigStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetL2StakeTogetherEvent {
  export type InputTuple = [l2StakeTogether: AddressLike];
  export type OutputTuple = [l2StakeTogether: string];
  export interface OutputObject {
    l2StakeTogether: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetValidatorSizeEvent {
  export type InputTuple = [newValidatorSize: BigNumberish];
  export type OutputTuple = [newValidatorSize: bigint];
  export interface OutputObject {
    newValidatorSize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawToL2Event {
  export type InputTuple = [
    amount: BigNumberish,
    minGasLimit: BigNumberish,
    extraData: BytesLike
  ];
  export type OutputTuple = [
    amount: bigint,
    minGasLimit: bigint,
    extraData: string
  ];
  export interface OutputObject {
    amount: bigint;
    minGasLimit: bigint;
    extraData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): IAdapter;
  waitForDeployment(): Promise<this>;

  interface: IAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addValidator: TypedContractMethod<
    [_publicKey: BytesLike, _signature: BytesLike, _depositDataRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  addValidatorOracle: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  forceNextValidatorOracle: TypedContractMethod<[], [void], "nonpayable">;

  isValidatorOracle: TypedContractMethod<
    [_account: AddressLike],
    [boolean],
    "view"
  >;

  removeValidatorOracle: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  setConfig: TypedContractMethod<
    [_config: IAdapter.ConfigStruct],
    [void],
    "nonpayable"
  >;

  withdrawToL2: TypedContractMethod<
    [amount: BigNumberish, minGasLimit: BigNumberish, extraData: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addValidator"
  ): TypedContractMethod<
    [_publicKey: BytesLike, _signature: BytesLike, _depositDataRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addValidatorOracle"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceNextValidatorOracle"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isValidatorOracle"
  ): TypedContractMethod<[_account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeValidatorOracle"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setConfig"
  ): TypedContractMethod<
    [_config: IAdapter.ConfigStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawToL2"
  ): TypedContractMethod<
    [amount: BigNumberish, minGasLimit: BigNumberish, extraData: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddValidator"
  ): TypedContractEvent<
    AddValidatorEvent.InputTuple,
    AddValidatorEvent.OutputTuple,
    AddValidatorEvent.OutputObject
  >;
  getEvent(
    key: "AddValidatorOracle"
  ): TypedContractEvent<
    AddValidatorOracleEvent.InputTuple,
    AddValidatorOracleEvent.OutputTuple,
    AddValidatorOracleEvent.OutputObject
  >;
  getEvent(
    key: "NextValidatorOracle"
  ): TypedContractEvent<
    NextValidatorOracleEvent.InputTuple,
    NextValidatorOracleEvent.OutputTuple,
    NextValidatorOracleEvent.OutputObject
  >;
  getEvent(
    key: "ReceiveEther"
  ): TypedContractEvent<
    ReceiveEtherEvent.InputTuple,
    ReceiveEtherEvent.OutputTuple,
    ReceiveEtherEvent.OutputObject
  >;
  getEvent(
    key: "RemoveValidatorOracle"
  ): TypedContractEvent<
    RemoveValidatorOracleEvent.InputTuple,
    RemoveValidatorOracleEvent.OutputTuple,
    RemoveValidatorOracleEvent.OutputObject
  >;
  getEvent(
    key: "SetConfig"
  ): TypedContractEvent<
    SetConfigEvent.InputTuple,
    SetConfigEvent.OutputTuple,
    SetConfigEvent.OutputObject
  >;
  getEvent(
    key: "SetL2StakeTogether"
  ): TypedContractEvent<
    SetL2StakeTogetherEvent.InputTuple,
    SetL2StakeTogetherEvent.OutputTuple,
    SetL2StakeTogetherEvent.OutputObject
  >;
  getEvent(
    key: "SetValidatorSize"
  ): TypedContractEvent<
    SetValidatorSizeEvent.InputTuple,
    SetValidatorSizeEvent.OutputTuple,
    SetValidatorSizeEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawToL2"
  ): TypedContractEvent<
    WithdrawToL2Event.InputTuple,
    WithdrawToL2Event.OutputTuple,
    WithdrawToL2Event.OutputObject
  >;

  filters: {
    "AddValidator(address,uint256,bytes,bytes,bytes,bytes32)": TypedContractEvent<
      AddValidatorEvent.InputTuple,
      AddValidatorEvent.OutputTuple,
      AddValidatorEvent.OutputObject
    >;
    AddValidator: TypedContractEvent<
      AddValidatorEvent.InputTuple,
      AddValidatorEvent.OutputTuple,
      AddValidatorEvent.OutputObject
    >;

    "AddValidatorOracle(address)": TypedContractEvent<
      AddValidatorOracleEvent.InputTuple,
      AddValidatorOracleEvent.OutputTuple,
      AddValidatorOracleEvent.OutputObject
    >;
    AddValidatorOracle: TypedContractEvent<
      AddValidatorOracleEvent.InputTuple,
      AddValidatorOracleEvent.OutputTuple,
      AddValidatorOracleEvent.OutputObject
    >;

    "NextValidatorOracle(uint256,address)": TypedContractEvent<
      NextValidatorOracleEvent.InputTuple,
      NextValidatorOracleEvent.OutputTuple,
      NextValidatorOracleEvent.OutputObject
    >;
    NextValidatorOracle: TypedContractEvent<
      NextValidatorOracleEvent.InputTuple,
      NextValidatorOracleEvent.OutputTuple,
      NextValidatorOracleEvent.OutputObject
    >;

    "ReceiveEther(uint256)": TypedContractEvent<
      ReceiveEtherEvent.InputTuple,
      ReceiveEtherEvent.OutputTuple,
      ReceiveEtherEvent.OutputObject
    >;
    ReceiveEther: TypedContractEvent<
      ReceiveEtherEvent.InputTuple,
      ReceiveEtherEvent.OutputTuple,
      ReceiveEtherEvent.OutputObject
    >;

    "RemoveValidatorOracle(address)": TypedContractEvent<
      RemoveValidatorOracleEvent.InputTuple,
      RemoveValidatorOracleEvent.OutputTuple,
      RemoveValidatorOracleEvent.OutputObject
    >;
    RemoveValidatorOracle: TypedContractEvent<
      RemoveValidatorOracleEvent.InputTuple,
      RemoveValidatorOracleEvent.OutputTuple,
      RemoveValidatorOracleEvent.OutputObject
    >;

    "SetConfig(tuple)": TypedContractEvent<
      SetConfigEvent.InputTuple,
      SetConfigEvent.OutputTuple,
      SetConfigEvent.OutputObject
    >;
    SetConfig: TypedContractEvent<
      SetConfigEvent.InputTuple,
      SetConfigEvent.OutputTuple,
      SetConfigEvent.OutputObject
    >;

    "SetL2StakeTogether(address)": TypedContractEvent<
      SetL2StakeTogetherEvent.InputTuple,
      SetL2StakeTogetherEvent.OutputTuple,
      SetL2StakeTogetherEvent.OutputObject
    >;
    SetL2StakeTogether: TypedContractEvent<
      SetL2StakeTogetherEvent.InputTuple,
      SetL2StakeTogetherEvent.OutputTuple,
      SetL2StakeTogetherEvent.OutputObject
    >;

    "SetValidatorSize(uint256)": TypedContractEvent<
      SetValidatorSizeEvent.InputTuple,
      SetValidatorSizeEvent.OutputTuple,
      SetValidatorSizeEvent.OutputObject
    >;
    SetValidatorSize: TypedContractEvent<
      SetValidatorSizeEvent.InputTuple,
      SetValidatorSizeEvent.OutputTuple,
      SetValidatorSizeEvent.OutputObject
    >;

    "WithdrawToL2(uint256,uint32,bytes)": TypedContractEvent<
      WithdrawToL2Event.InputTuple,
      WithdrawToL2Event.OutputTuple,
      WithdrawToL2Event.OutputObject
    >;
    WithdrawToL2: TypedContractEvent<
      WithdrawToL2Event.InputTuple,
      WithdrawToL2Event.OutputTuple,
      WithdrawToL2Event.OutputObject
    >;
  };
}
