/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakeTogetherV1Sol from "./StakeTogetherV1.sol";
export type { stakeTogetherV1Sol };
export type { StakeTogetherV2 } from "./StakeTogetherV2";
export type { StakeTogetherV3 } from "./StakeTogetherV3";
export type { StakeTogetherV4 } from "./StakeTogetherV4";
