name: Rules Validator

on:
  push:
    branches:
      - '**'
jobs:
  validate_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Check Branch
        run: echo ${GITHUB_REF#refs/heads/}

      - name: Create .env file
        run: |
          touch .env
          echo NEXT_PUBLIC_CHAIN_ID=1 >> .env          
          echo NEXT_PUBLIC_GA_MEASUREMENT_ID=1 >> .env
          echo NEXT_PUBLIC_CLOUDFLARE_TOKEN=1 >> .env
          echo NEXT_PUBLIC_HOTJAR_ID=1 >> .env
          echo NEXT_PUBLIC_MIXPANEL_ID=1 >> .env
          echo NEXT_PUBLIC_WEB3_AUTH_ID=1 >> .env
          echo NEXT_PUBLIC_WALLET_CONNECT=1 >> .env
          echo NEXT_PUBLIC_WEB3_AUTH_ID=1 >> .env
          echo NEXT_PUBLIC_FIREBASE_CREDENTIALS_CLIENT_EMAIL=1 >> .env
          echo NEXT_PUBLIC_FIREBASE_CREDENTIALS_PRIVATE_KEY=1 >> .env
          echo NEXT_PUBLIC_FIREBASE_CREDENTIALS_PROJECT_ID=1 >> .env
          echo NEXT_PUBLIC_CONTENTFUL_TOKEN=1 >> .env
          echo NEXT_PUBLIC_CONTENTFUL_SPACE=1 >> .env
          echo NEXT_PUBLIC_RPC_HOLESKY_SEPOLIA_URL=1 >> .env
          echo NEXT_PUBLIC_RPC_MAINNET=1 >> .env
          echo NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=1 >> .env
          echo NEXT_PUBLIC_CONTENTFUL_CMA_TOKEN=1 >> .env
          echo NEXT_PUBLIC_TRANSAK_API_KEY=1 >> .env
          echo NEXT_PUBLIC_WEB3_DEVNET_AUTH_ID=1 >> .env
          echo NEXT_PUBLIC_RPC_OPTIMIST_SEPOLIA_URL=1 >> .env
          echo NEXT_PUBLIC_RPC_MAINNET_URL=https://eth-mainnet.g.alchemy.com/v2/maUdOba2Td2ntuB3ry2hwJlW3RGkrJjx >> .env
      - name: Install dependencies
        run: pnpm install

      - name: Check text Formatting
        run: pnpm prettier

      - name: Check text Grammar
        run: pnpm cspell

      - name: Check Lint Rules
        run: pnpm lint

      - name: Perform Build
        run: pnpm build
